리그 조회 API 구현 / 리그 저장 method 구현
Easy-Easy-Go/Glol-Server pull request #5
Opened 2022-10-26 11:28 UTC by honghyunin

# 작업 사항

- 리그 조회 API 구현
- 리그 저장 method 구현

![image](https://user-images.githubusercontent.com/68847615/198014775-f6f3dae5-3fcf-4ad3-9463-488e9c9e2589.png)

2022-11-02 12:50 UTC, ckrudals requested changes
수고하셨습니다.
비동기 처리 코드 기대하겠습니다.

2022-11-02 12:50 UTC, ckrudals commented on build.gradle.kts
주석을 왜 다셔는지는 모르겠지만 현재 상황에서 안쓰이는 것 이라면 지우는게 좋을 것 같아요.

2022-11-02 12:50 UTC, ckrudals commented on src/main/kotlin/com/server/glol/domain/league/service/facade/impl/LeagueServiceFacadeImpl.kt
> +
line break 지워주세요.

2022-11-02 12:50 UTC, ckrudals commented on src/main/kotlin/com/server/glol/domain/league/service/facade/impl/LeagueServiceFacadeImpl.kt
> +class LeagueServiceFacadeImpl(
Impl 같은 prefix는 [anti pattern](https://octoperf.com/blog/2016/10/27/impl-classes-are-evil/#the-list-example) 이라고 합니다.
현재 이 service가 어떠한 역할을 하는진 모르겠지만.
RemoteLeagueServiceFacade 로 이름을 바꾸는 것은 어떨까요?

추가적인 질문사항 :  Facadde는 어떨 때 사용되는 prefix인가요?

2022-11-02 12:50 UTC, ckrudals commented on src/main/kotlin/com/server/glol/domain/league/service/impl/LeagueServiceImpl.kt
> +        const val SOLO_RANK = "RANKED_SOLO_5x5"
저 상수들이 현재 이 class에서만 사용된다면 어디서든 접근 가능한 companion object 보단 
```kotlin
 private const val FREE_RANK = "RANKED_FLEX_SR"
 private const val SOLO_RANK = "RANKED_SOLO_5x5"
 ``` 
 로 class 아래에 사용하시는건 어떨까요?
 
 그리고 푸쉬하기전에 코드 재정렬 해주세요 😊

2022-11-02 12:50 UTC, ckrudals commented on src/main/kotlin/com/server/glol/domain/league/service/impl/LeagueServiceImpl.kt
> +            val summoner = summonerServiceFacade.getSummoner(name)
알고 계실 수 있지만. if 문 같은 것도 [single functional](https://kotlinlang.org/docs/idioms.html#single-expression-functions) 이 가능합니다.
```kotlin
   override fun getLeague(name: String): MutableSet<LeagueDto> =
            if (!summonerRepository.existsSummonerByName(name)) {
                val summoner = summonerServiceFacade.getSummoner(name)

                leagueServiceFacade.getLeague(summoner.id)
            } else {
                leagueCustomRepository.getLeagueEntryByName(name)
            }
```

2022-11-02 12:50 UTC, ckrudals commented on src/main/kotlin/com/server/glol/domain/league/service/impl/LeagueServiceImpl.kt
> +        leagueDto.map { dto ->
dto 라는 반한값 보다는 제 추측으로 league 가 더 올바른 반한값 인 것 같습니다.
명시적으로 적어주시면 코드 볼때 이해가 수월해집니다.!

2022-11-14 02:31 UTC, honghyunin commented on src/main/kotlin/com/server/glol/domain/league/service/facade/impl/LeagueServiceFacadeImpl.kt
> +class LeagueServiceFacadeImpl(
> Impl 같은 prefix는 [anti pattern](https://octoperf.com/blog/2016/10/27/impl-classes-are-evil/#the-list-example) 이라고 합니다.
> 현재 이 service가 어떠한 역할을 하는진 모르겠지만.
> RemoteLeagueServiceFacade 로 이름을 바꾸는 것은 어떨까요?

Impl이 왜 anti pattern 이라고 하는 지 이해했습니다.
하지만 이 Impl을 왜 사용해야하는 지 해당 패턴에 대해 조금 설명드리자면,

인터페이스를 사용함으로써 메서드(기능)에 대한 명세를 제시하고,
이를 구현하는 구현 클래스로 그 기능을 구현하여, 
명세와 구현의 책임을 나누어 개발하는 것입니다.

또한 interface를 사용함으로써 하나의 기능을 여러 방식으로 구현할 수 있습니다.
서비스 로직이 변경되더라도 이 서비스 로직을 사용하는 클라이언트 코드들은 변경 없이 그대로 사용할 수 있습니다.

단순히 현재로써는 불필요한 파일의 추가일 수 있겠지만
추후에 있을 기능 확장에 대비하기 위해 사용하고 있습니다.

Facade 패턴은 보통 반복적으로 여러 라이브러리의 함수를 사용하는 복잡도 높은 코드를 단순화 시킬 때 사용합니다.

`LeagueServiceFacadeImpl` 클래스는 WebClient(외부 API 호출 라이브러리)로 Riot API에 접근하는 기능을 합니다.
저희 서비스는 기본적으로 Riot API에 의존하고 있기 때문에 이러한 코드들이 필요합니다. 하지만 반복적으로 유사한 코드를 사용하기 보다 Facade 패턴으로 분리하여 재사용성을 높여 사용하는 것이 더 유용하다고 보아 Facade 패턴을 사용했습니다.

따라서 외부 API를 의존하는 `LeagueServiceFacadeImpl` 과 같은 코드에 경민님 말씀대로 Remote 키워드를 붙이겠습니다.

2022-11-21 23:29 UTC, merged